services:
  app:
    image: python:3.10-slim
    container_name: coinx
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - PIP_INDEX_URL=${PIP_INDEX_URL}
    command: sh -c "pip install -r requirements.txt && pip install -e . && python -m coinx.main"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - "5000:5000"
